/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: '**.gstatic.com' },
      { protocol: 'https', hostname: 'otopoint.com.tr' },
      { protocol: 'https', hostname: '**.fiatbayi.com.tr' },
      { protocol: 'https', hostname: '**.citroenorigins.fr' },
      { protocol: 'https', hostname: '**.alanyatekmar.com' },
      { protocol: 'https', hostname: '**.cardekho.com' },
      { protocol: 'https', hostname: '**.otokoc.com.tr' },
      { protocol: 'https', hostname: '**.tripadvisor.com' },
      { protocol: 'https', hostname: '**.getyourguide.com' },
      { protocol: 'https', hostname: '**.touralanya.com' },
      { protocol: 'https', hostname: '**.agentis.com.tr' },
      { protocol: 'https', hostname: '**.dsmcdn.com' },
      { protocol: 'https', hostname: '**.tatilsepeti.com' },
      { protocol: 'https', hostname: '**.trav3l.net' },
      { protocol: 'https', hostname: '**.vigotours.com' },
      { protocol: 'https', hostname: '**.etstur.com' },
      { protocol: 'https', hostname: '**.tatilbudur.com' },
      { protocol: 'https', hostname: '**.wixstatic.com' },
      { protocol: 'https', hostname: '**.excursionside.com' },
      { protocol: 'https', hostname: '**.goreme.com' },
      { protocol: 'https', hostname: '**.midtown-hotel.com' },
      { protocol: 'https', hostname: '**.turkishbaths.org' },
      { protocol: 'https', hostname: 'i.imgur.com' },
      { protocol: 'https', hostname: 'alanyadailytours.com' },
      { protocol: 'https', hostname: '**.didimtour.com' },
      { protocol: 'https', hostname: '**.stokedtotravel.com' },
      { protocol: 'https', hostname: '**.pamukkale.com.tr' },
      { protocol: 'https', hostname: 'kekovatekneturu.com' },
      { protocol: 'https', hostname: 'gunluktur.net' },
      { protocol: 'https', hostname: 'seastartravel.com.tr' },
      { protocol: 'https', hostname: '**.gezinoktasi.com.tr' },
      { protocol: 'https', hostname: '**.zengardentr.com' },
      { protocol: 'https', hostname: '**.freetour.com' },
      { protocol: 'https', hostname: '**.dailytoursinalanya.com' },
      { protocol: 'https', hostname: '**.visitscotland.com' },
      { protocol: 'https', hostname: '**.argeya.com' },
      { protocol: 'https', hostname: '**.alanya-tours.com' },
      { protocol: 'https', hostname: 'tursaytravel.com' },
      { protocol: 'https', hostname: '**.elitema.com.tr' },
      { protocol: 'https', hostname: '**.ziparizona.com' },
      { protocol: 'https', hostname: '**.tacdn.com' },
      { protocol: 'https', hostname: '**.campingsannecy.com' },
      { protocol: 'https', hostname: '**.klook.com' },
      { protocol: 'https', hostname: '**.cloudfront.net' },
      { protocol: 'https', hostname: '**.side-tours.com' },
      { protocol: 'https', hostname: '**.sencaptour.com' },
      { protocol: 'https', hostname: 'bikestore.becdn.net' },
      { protocol: 'https', hostname: 'upload.wikimedia.org' }
    ].map(pattern => ({ ...pattern, port: '', pathname: '/**' }))
  },
};

export default nextConfig;
